In [1]:
import torch
from torch.nn import CrossEntropyLoss

/opt/conda/envs/ingenious/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
nBatch = 128
nClass = 30522
nTokens = 128

In [3]:
prediction_logits=torch.randn (nBatch, nTokens, nClass).to("cuda")

In [4]:
targets=torch.randint (nClass, (nBatch, nTokens)).to("cuda")

In [5]:
loss_fct=CrossEntropyLoss(reduction="none")
loss=loss_fct(torch.transpose(prediction_logits,1,2), targets)
loss.mean()

tensor(10.8278, device='cuda:0')

In [6]:
loss_fct=CrossEntropyLoss()
loss=loss_fct(torch.transpose(prediction_logits,1,2), targets)
loss

tensor(10.8278, device='cuda:0')

In [7]:
X=torch.tensor(
    [[1,2,3],
    [4,5,6],
    [7,8,9]]
)

In [8]:
mask=(X%2==0)

In [10]:
mask

tensor([[False,  True, False],
        [ True, False,  True],
        [False,  True, False]])

In [9]:
X*mask

tensor([[0, 2, 0],
        [4, 0, 6],
        [0, 8, 0]])

In [11]:
(X*mask).sum(dim=1)/(mask.sum(dim=1))

tensor([2., 5., 8.])